spring:
  jpa:
    hibernate:
      ddl-auto: none
  h2:
    console:
      enabled: true

logging:
  pattern:
    console: "%d %-5level %logger : %msg%n"
    file: "%d %-5level [%thread] %logger : %msg%n"
  level:
    org.hibernate: debug
    com.messio: debug

server:
  port: 8080
