spring:
  datasource:
    url: jdbc:mysql://localhost/mini
    driverClassName: com.mysql.jdbc.Driver
    username: training
    password: training
    pool-size: 30
    platform: org.hibernate.dialect.MySQLDialect
  jpa:
    hibernate:
      ddl-auto: create

logging:
  pattern:
    console: "%d %-5level %logger : %msg%n"
    file: "%d %-5level [%thread] %logger : %msg%n"
  level:
    org.hibernate: info
    com.messio: debug

server:
  port: 8080
