package com.messio.mini.entity;

/**
 * Created by jpc on 1/20/15.
 */
public enum FirstAction {
    ADMINISTRATIVE_HEARINGS,
    OPPOSITION,
    EX_PARTE_REEXAMINATION_PETITION,
    PTO_REEXAMINATION,
    INTER_PARTES_REVIEW_PETITION,
    POST_GRANT_REVIEW_PETITION,
    PETITION_UNDER_TRANSITIONAL_PROGRAM,
    DERIVATION_PROCEEDING,
    INTERFERENCE,
    INVALIDITY_CANCELLATION,
    REVOCATION,
    INFRINGEMENT,
    DECLARATORY,
    EMPLOYEE_INVENTION,
    OWNERSHIP,
    CONTRACT,
    TRIAL_FOR_CORRECTION,
    TRIAL_FOR_SCOPE,
    RETRIAL,
    CRIMINAL_ACTION,
    OTHER
}
